### PR TITLE
 Solved - Add more resources in the Resources Section #71

### PR DESCRIPTION
**Pull request by ayu5hagarwal**

### CODE REVIEW

**Comment by arncv** [comment]
NoFap resource looks good! Thank you for contributing. Merging🚀

**Comment by ayu5hagarwal** [comment]
There are some more problems modals from 2 to 10 share is not working.

**Comment by ayu5hagarwal** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> Name 	Status 	Preview 	Comments 	Updated (UTC)
> **intima** 	✅ Ready ([Inspect](https://vercel.com/arncv/intima/6pTUPTxGrE9dFcMdGAX6w26xNtAu)) 	[Visit Preview](https://vercel.live/open-feedback/intima-git-fork-ayu5hagarwal-modal11-arncv.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 	💬 [**Add feedback**](https://vercel.live/open-feedback/intima-git-fork-ayu5hagarwal-modal11-arncv.vercel.app?via=pr-comment-feedback-link) 	Oct 10, 2023 2:13pm



> Someone is attempting to deploy a commit to a Personal Account owned by @arncv on [Vercel](https://vercel.com).
> 
> @arncv first needs to [authorize it](https://vercel.com/git/authorize?type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22139c36c117717afdf17eff1e6840c9e05c9925c6%22%7D%2C%22id%22%3A%22QmemscqbRUXJz2aoo1vhXVytbbmrjJcjjb1zDyzoMNrVUc%22%2C%22org%22%3A%22arncv%22%2C%22prId%22%3A80%2C%22repo%22%3A%22Intima%22%7D).

@arncv  can you authorize it.

**Comment by arncv** [comment]
@ayu5hagarwal I have authorized it and it has been added in hacktoberfest. Yeah the copy link button is not working right now, will put an issue soon.

**Pull request merged**
