### PR TITLE
added a interactive quiz section

### PR DESCRIPTION
**Pull request by TusharGagal**
I have added a interactive quiz section and at last it will give a result and give a feedback.
glimpse of a quiz:
image
image
image

thank you for this contribution.

### CODE REVIEW

**Comment by TusharGagal** [comment]
Now check is it correct.

**Comment by arncv** [comment]
I fixed the conflict arising from a recent pull request. 
It works great now, merging it!🚀
Thank you for your contribution! Happy Hacktoberfest 😄

**Comment by TusharGagal** [comment]
All checks are not passed for this pr will it considered in hacktoberfest ??

**Comment by arncv** [comment]
> All checks are not passed for this pr will it considered in hacktoberfest ??

As your pr is merged in the main branch now, It will be considered for hacktoberfest

**Comment by TusharGagal** [comment]
someone has changes the whole ui of quiz which looks very bad than before.

**Comment by TusharGagal** [comment]
is there any impact of my contribution so that i can add it to my resume ?

**Pull request merged**
