### PR TITLE
Added a Dark Mode option on home page but it works on double-click

### PR DESCRIPTION
**Pull request by Chitresh-code**
I added the dark mode feature on the Home Page of the website.
The only problem is that it works when clicked twice.

### CODE REVIEW

**Comment by arncv** [comment]
Hey @Chitresh-code  I've noticed a few more bugs related to it:

When dark mode is enabled, the colors of icons and photos on the website are inverted.
The navigation bar remains in light mode even when dark mode is turned on.

Should I create a new issue for these bugs or would you like to take care of them?

Other than that, the implementation looks great! Thank you for your contribution!

**Comment by Chitresh-code** [comment]
I can fix those too, I'll just need some time.
Also do you need the dark mode for other pages and the bot too or just the home page?

**Comment by arncv** [comment]
Only the home page works, the bot's page is getting a theme/style change and we can enable dark mode there in future issues

**Comment by Chitresh-code** [comment]
I changed the code a little for the colour of images and icons, see if they are still inverting.
If the error continues then remove the following code from the very end of css/styles.css:
.darkmode-layer, .darkmode-toggle {
  z-index: 500;
}
Then see if it helps

**Comment by arncv** [comment]
Hey @Chitresh-code, great job adding the dark mode feature on the Home Page! I really appreciate your contribution. By the way, I went ahead and removed the darkmode.css code since it was causing the SVG image to invert. Don't worry about it though, I'll merge the PR. Thanks again for your awesome work!

**Comment by Chitresh-code** [comment]
Hey @arncv thanks for the opportunity.

If you would like to optimise the website using bootstrap for mobile view, you can put up an issue and I would be happy to work on it.

As I saw, in mobile view thw dark mode logo also deforms. Will be happy to work on it.
Thanks

**Comment by arncv** [comment]
@Chitresh-code Sure, I'll put up a issue regarding that! Happy Hacktoberfest!

**Pull request merged**
